arguments:
    transport: Innmind\HttpTransport\Transport
    clock: '?Innmind\TimeContinuum\TimeContinuumInterface'
    reader: '?Innmind\Xml\Reader'
    urlResolver: '?Innmind\UrlResolver\ResolverInterface'
    parser: Innmind\Crawler\Parser ?? $parser.default

expose:
    crawler: $crawler

services:
    crawler Innmind\Crawler\Crawler\Crawler:
        - '$transport'
        - '$parser'

    resolver Innmind\Crawler\UrlResolver:
        - '$urlResolver'

    parser:
        default Innmind\Crawler\Parser\SequenceParser:
            - '$parser.http.contentType'
            - '$parser.http.cache'
            - '$parser.html.base'
            - '$parser.alternates'
            - '$parser.canonical'
            - '$parser.charset'
            - '$parser.languages'
            - '$parser.html.openGraph.image'
            - '$parser.html.openGraph.type'
            - '$parser.html.title'
            - '$parser.html.anchors'
            - '$parser.html.android'
            - '$parser.html.author'
            - '$parser.html.citations'
            - '$parser.html.content'
            - '$parser.html.description'
            - '$parser.html.images'
            - '$parser.html.ios'
            - '$parser.html.journal'
            - '$parser.html.links'
            - '$parser.html.rss'
            - '$parser.html.themeColor'
            - '$parser.image.dimension'
            - '$parser.image.weight'

        alternates Innmind\Crawler\Parser\AlternatesParser:
            - '$parser.http.alternates'
            - '$parser.html.alternates'

        canonical Innmind\Crawler\Parser\ConditionalParser:
            - '$parser.html.openGraph.url'
            - '$parser.html.canonical'
            - '$parser.http.canonical'

        charset Innmind\Crawler\Parser\ConditionalParser:
            - '$parser.html.charset'
            - '$parser.http.charset'

        languages Innmind\Crawler\Parser\ConditionalParser:
            - '$parser.html.languages'
            - '$parser.http.languages'

        http:
            contentType Innmind\Crawler\Parser\Http\ContentTypeParser: []

            cache Innmind\Crawler\Parser\Http\CacheParser:
                - '$clock'

            alternates Innmind\Crawler\Parser\Http\AlternatesParser:
                - '$resolver'

            canonical Innmind\Crawler\Parser\Http\CanonicalParser:
                - '$resolver'

            charset Innmind\Crawler\Parser\Http\CharsetParser: []

            languages Innmind\Crawler\Parser\Http\LanguagesParser: []

        html:
            base Innmind\Crawler\Parser\Html\BaseParser:
                - '$reader'

            alternates Innmind\Crawler\Parser\Html\AlternatesParser:
                - '$reader'
                - '$resolver'

            canonical Innmind\Crawler\Parser\Html\CanonicalParser:
                - '$reader'
                - '$resolver'

            charset Innmind\Crawler\Parser\Html\CharsetParser:
                - '$reader'

            languages Innmind\Crawler\Parser\Html\LanguagesParser:
                - '$reader'

            title Innmind\Crawler\Parser\Html\TitleParser:
                - '$reader'

            anchors Innmind\Crawler\Parser\Html\AnchorsParser:
                - '$reader'

            android Innmind\Crawler\Parser\Html\AndroidParser:
                - '$reader'

            author Innmind\Crawler\Parser\Html\AuthorParser:
                - '$reader'

            citations Innmind\Crawler\Parser\Html\CitationsParser:
                - '$reader'

            content Innmind\Crawler\Parser\Html\ContentParser:
                - '$reader'

            description Innmind\Crawler\Parser\Html\DescriptionParser:
                - '$reader'

            images Innmind\Crawler\Parser\Html\ImagesParser:
                - '$reader'
                - '$resolver'

            ios Innmind\Crawler\Parser\Html\IosParser:
                - '$reader'

            journal Innmind\Crawler\Parser\Html\JournalParser:
                - '$reader'

            links Innmind\Crawler\Parser\Html\LinksParser:
                - '$reader'
                - '$resolver'

            rss Innmind\Crawler\Parser\Html\RssParser:
                - '$reader'
                - '$resolver'

            themeColor Innmind\Crawler\Parser\Html\ThemeColorParser:
                - '$reader'

            openGraph:
                url Innmind\Crawler\Parser\Html\OpenGraph\UrlParser:
                    - '$reader'

                image Innmind\Crawler\Parser\Html\OpenGraph\ImageParser:
                    - '$reader'

                type Innmind\Crawler\Parser\Html\OpenGraph\TypeParser:
                    - '$reader'

        image:
            dimension Innmind\Crawler\Parser\Image\DimensionParser: []

            weight Innmind\Crawler\Parser\Image\WeightParser: []
